version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: investment_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: investment_platform
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 20s
      retries: 10

volumes:
  mysql_dev_data: