version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: investment_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: investment_platform
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: investment_backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: investment_platform
      DB_USER: app_user
      DB_PASSWORD: app_password
      JWT_SECRET: production-jwt-secret-change-this
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: .
    container_name: investment_frontend
    environment:
      VITE_API_BASE_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data: